// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQyH8tWzuNGgeGuibtsUsENfsR3OhZLIo',
    appId: '1:605410093928:web:8f10f68dc96a96e66d04dd',
    messagingSenderId: '605410093928',
    projectId: 'lilstex-handnote',
    authDomain: 'lilstex-handnote.firebaseapp.com',
    storageBucket: 'lilstex-handnote.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsvFzl0gYD5OfvZpyB95xYzFgRcIIhhEo',
    appId: '1:605410093928:android:845f94f9fa6305b66d04dd',
    messagingSenderId: '605410093928',
    projectId: 'lilstex-handnote',
    storageBucket: 'lilstex-handnote.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdLiEuPfqYgZz8uhFYzMke-agnCtygl7A',
    appId: '1:605410093928:ios:51c288b2628186a46d04dd',
    messagingSenderId: '605410093928',
    projectId: 'lilstex-handnote',
    storageBucket: 'lilstex-handnote.appspot.com',
    iosClientId: '605410093928-t2bb26hjirvbec8g6rs95rsc6dnevi0v.apps.googleusercontent.com',
    iosBundleId: 'ng.net.emmanuelmbagwu.handnote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdLiEuPfqYgZz8uhFYzMke-agnCtygl7A',
    appId: '1:605410093928:ios:f5a660d5b8f8d2eb6d04dd',
    messagingSenderId: '605410093928',
    projectId: 'lilstex-handnote',
    storageBucket: 'lilstex-handnote.appspot.com',
    iosClientId: '605410093928-858d420qt3u1tg4mtke8usn3e9dqfc18.apps.googleusercontent.com',
    iosBundleId: 'ng.net.emmanuelmbagwu.handnote.RunnerTests',
  );
}
